### ISSUE TITLE
测试发现好像并不支持上下文关联能力

### ISSUE THREAD

**Issue by zjrwtx** [IMxingyus/Cn-NewBing#7]

**Comment by JacobHu0723** [comment]
没有吧，那应该是微软那边的事。用网页版有时候也会忘了上文。都怪微软把New Bing给削傻了

**Comment by zjrwtx** [comment]
嗯嗯，现在测试其他问题后发现是支持的，谢谢

> 没有吧，那应该是微软那边的事。用网页版有时候也会忘了上文。都怪微软把New Bing给削傻了
